# Generated by Django 6.0.4 on 2026-05-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_status'),
        ('courses', '0025_alter_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course associated with this campaign. If selected, a batch will be auto-created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='courses.course'),
        ),
    ]
