# Generated by Django 6.0.4 on 2026-05-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadManagement', '0001_initial'),
        ('campaign', '0002_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaign.campaign'),
        ),
    ]
