# Generated by Django 6.0.4 on 2026-05-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_status'),
        ('courses', '0024_assignment_created_by_assignment_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='campaign.campaign', null=True),
        ),
    ]
