# Generated by Django 6.0.4 on 2026-05-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_course'),
        ('courses', '0025_alter_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='campaign.campaign'),
        ),
    ]
