# Generated by Django 6.0.4 on 2026-05-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
        ('LeadManagement', '0002_lead_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('demo_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_attendances', to='Demo.demoschedule')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_attendances', to='LeadManagement.lead')),
            ],
            options={
                'unique_together': {('demo_schedule', 'lead')},
            },
        ),
    ]
