# Generated by Django 6.0.4 on 2026-05-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Demo", "0003_add_status_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoschedule",
            name="parent_demo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reschedules",
                to="Demo.demoschedule",
            ),
        ),
        migrations.AlterField(
            model_name="demoschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("attended", "Attended"),
                    ("rescheduled", "Rescheduled"),
                    ("completed", "Completed"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
