# Generated by Django 6.0.4 on 2026-05-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LeadManagement', '0002_lead_campaign'),
        ('courses', '0024_assignment_created_by_assignment_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('fee_status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='courses.course')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_enrollments', to='LeadManagement.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('lead', 'course', 'enrollment_date')},
            },
        ),
    ]
