# Generated by Django 6.0.4 on 2026-05-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0001_initial'),
        ('courses', '0026_alter_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('course_type', models.CharField(choices=[('Training', 'Training'), ('Industry Readiness', 'Industry Readiness')], default='Training', max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('current_status', models.CharField(choices=[('Student', 'Student'), ('Working Professional', 'Working Professional'), ('Job Seeker', 'Job Seeker')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
                ('preferred_batch_timing', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=50)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('fee_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=20)),
                ('enrollment_date', models.DateField()),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_app_enrollments', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LeadEnrollment',
        ),
    ]
