# Generated by Django 6.0.4 on 2026-05-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0002_enrollment_delete_leadenrollment'),
        ('LeadManagement', '0002_lead_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enrollments', to='LeadManagement.lead'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
