# Generated by Django 6.0.4 on 2026-05-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0004_enrollment_is_active_enrollment_payment_status_and_more'),
        ('courses', '0026_alter_batch_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('email', 'course')},
        ),
    ]
